Linux: '/home/naina/Documents/cdk/components/rhel/'
Mac : ''
CYGWIN_NT-10.0 : '/cygdrive/c/Users/naina/Downloads/TestingBuilds/rc5/cdk/components/rhel/'
#CYGWIN_NT-10.0 : '/cygdrive/c/Users/naina/Downloads/TestingBuilds/rc5/cdk/components/rhel/'
vagrant_RHN_USERNAME: 'naverma@redhat.com'
vagrant_RHN_PASSWORD: '******************'
vagrant_PLUGINS_DIR: 'C:/Users/naina/Downloads/TestingBuilds/rc5/cdk/plugins/'
vagrant_VARGRANTFILE_DIRS: 'C:/Users/naina/Downloads/TestingBuilds/rc5/cdk/components/rhel/'
vagrant_BOX_PATH: 'C:/Users/naina/Downloads/TestingBuilds/rc5/rhel-cdk-kubernetes-7.2-26.x86_64.vagrant-hyperv.box'
SudoPassword: 'm0m'
Latest_build_link: 'http://cdk-builds.usersys.redhat.com/builds/nightly/latest-build/'
vagrant_PROVIDER: 'hyperv'
Windows_Shell : 'cmd'
vagrant_UP_FILES: 'misc/hyperv/rhel-k8s-singlenode-hyperv,misc/hyperv/rhel-ose-hyperv,rhel-ose,misc/rhel-k8s-singlenode-setup'
